### ISSUE TITLE
problème au lancement de l'application

### ISSUE THREAD

**Issue by DavidStevenoot** [atoulmet/atoulmet-OC-React-Beginners#3]
Je n'arrive pas à lancer l'application au yarn start et il n'y a aucune explication dans le README dans ce cas particulier
J'ai ce message d'erreur qui se produit

```
node:internal/modules/cjs/loader:528
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in C:\atoulmet-OC-React-Beginners\node_modules\postcss-safe-parser\node_modules\postcss\package.json
```

**Comment by atoulmet** [comment]
Bonjour, je compte justement faire une mise à jour du projet. Je vais y jeter un oeil !

**Comment by atoulmet** [comment]
Je viens de tester, il n'y a pas de soucis à lancer le projet sur les branches sur lesquelles j'a travaillé. Sur quelle branche étiez vous ?

**Comment by DavidStevenoot** [comment]
Je suis sur la branche master

**Comment by DavidStevenoot** [comment]
Autant pour moi, je n'avais pas initialisé le projet avec `npx create-react-app la-maison-jungle`
Il a fallu que je mette à jour les dépendances avec un `yarn` et que je corrige une erreur avec `yarn add react-scripts`
